# Generated by Django 2.1.7 on 2019-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=1000)),
                ('student_id', models.CharField(max_length=1000)),
                ('student_roll', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
