# Generated by Django 2.1.7 on 2019-04-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cse',
            fields=[
                ('dsa', models.FloatField()),
                ('oops', models.FloatField()),
                ('dbms', models.FloatField()),
                ('Computer_Networks', models.FloatField()),
                ('os', models.FloatField()),
                ('communication', models.FloatField()),
                ('jee_mains', models.FloatField()),
                ('cp', models.FloatField()),
                ('student_roll', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGen',
            fields=[
                ('student_roll', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('percentage_in_10th', models.FloatField()),
                ('percentage_in_12th', models.FloatField()),
                ('current_CGPA', models.FloatField()),
                ('year_of_birth', models.FloatField()),
                ('expected_year_of_placement', models.FloatField()),
                ('passing_year_of_10th', models.FloatField()),
                ('passing_year_of_12th', models.FloatField()),
                ('Board_10th', models.IntegerField()),
                ('Board_12th', models.IntegerField()),
                ('BTech_Branch', models.IntegerField()),
                ('Category', models.IntegerField()),
                ('Fathers_Occupation', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Mothers_Occupation', models.IntegerField()),
                ('Permanent_address', models.IntegerField()),
                ('type_of_disability', models.IntegerField()),
            ],
        ),
    ]
