# Generated by Django 2.1.7 on 2019-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190406_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CseRating',
            fields=[
                ('dsa', models.FloatField(default=10)),
                ('oops', models.FloatField(default=10)),
                ('dbms', models.FloatField(default=10)),
                ('Computer_Networks', models.FloatField(default=10)),
                ('os', models.FloatField(default=10)),
                ('communication', models.FloatField(default=10)),
                ('jee_mains', models.FloatField(default=10)),
                ('cp', models.FloatField(default=10)),
                ('compiler', models.FloatField(default=10)),
                ('student_roll', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('student_background', models.FloatField(default=10)),
            ],
        ),
    ]
