# Generated by Django 2.1.7 on 2019-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_cserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cserating',
            name='placement_status',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentgen',
            name='placement_chance',
            field=models.FloatField(default=0.5),
        ),
    ]
